# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/fpga/lab4/add/add.cache/wt [current_project]
set_property parent.project_path C:/fpga/lab4/add/add.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths c:/Users/agazor/AppData/Roaming/Xilinx/Vivado/Lab4 [current_project]
update_ip_catalog
set_property ip_output_repo c:/fpga/lab4/add/add.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/hdl/design_3_wrapper.vhd
add_files C:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/design_3.bd
set_property used_in_implementation false [get_files -all c:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/ip/design_3_greatest_common_fact_0_0/constraints/greatest_common_factor_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/ip/design_3_xbar_0/design_3_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/ip/design_3_processing_system7_0_0/design_3_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/ip/design_3_rst_ps7_0_50M_0/design_3_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/ip/design_3_rst_ps7_0_50M_0/design_3_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/ip/design_3_rst_ps7_0_50M_0/design_3_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/ip/design_3_auto_pc_1/design_3_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/fpga/lab4/add/add.srcs/sources_1/bd/design_3/design_3_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_3_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_3_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_3_wrapper_utilization_synth.rpt -pb design_3_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
