# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_3/design_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_greatest_common_fact_0_0/design_3_greatest_common_fact_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_greatest_common_fact_0_0 || ORIG_REF_NAME==design_3_greatest_common_fact_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xbar_0/design_3_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_xbar_0 || ORIG_REF_NAME==design_3_xbar_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_interconnect_0_0/design_3_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_axi_interconnect_0_0 || ORIG_REF_NAME==design_3_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_processing_system7_0_0/design_3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_processing_system7_0_0 || ORIG_REF_NAME==design_3_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rst_ps7_0_50M_0/design_3_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_3_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_pc_1/design_3_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_auto_pc_1 || ORIG_REF_NAME==design_3_auto_pc_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_auto_pc_0 || ORIG_REF_NAME==design_3_auto_pc_0} -quiet] -quiet

# XDC: bd/design_3/design_3_ooc.xdc
